import { Router } from "express";
import { sarlRoute } from "./sarl";
import { sarluRoute } from "./sarlu";
import { saAgRoute } from "./sa-ag";
import { saUniRoute } from "./sa-uni";
import { saCaRoute } from "./sa-ca";
import { sasuRoute } from "./sasu";
import { sasRoute } from "./sas";
import { gieRoute } from "./gie";
import { stePartRoute } from "./ste-part";
import { drcRoute } from "./drc";
import { pvAgoRoute } from "./pv-ago";
import { pvAgeRoute } from "./pv-age";
import { convAgoRoute } from "./conv-ago";
import { convAgeRoute } from "./conv-age";
import { pouvoirAgRoute } from "./pouvoir-ag";
import { feuillePresenceRoute } from "./feuille-presence";
import { rapportGestionRoute } from "./rapport-gestion";
import { pouvoirCaRoute } from "./pouvoir-ca";
import { avisConvocationAgSaRoute } from "./avis-convocation-ag-sa";
import { convocationActionnairesSaRoute } from "./convocation-actionnaires-sa";
import { lettreInfoCaConventionsRoute } from "./lettre-info-ca-conventions";
import { avisCacConventionsSaRoute } from "./avis-cac-conventions-sa";
import { avisCacConventionsSarlRoute } from "./avis-cac-conventions-sarl";
import { feuillePresenceCaRoute } from "./feuille-presence-ca";
import { lettreConsultationGeranceRoute } from "./lettre-consultation-gerance";
import { pvConsultationEcriteRoute } from "./pv-consultation-ecrite";
import { decAssocieUniqueGerantRoute } from "./dec-associe-unique-gerant";
import { decAssocieUniqueNonGerantRoute } from "./dec-associe-unique-non-gerant";
import { pvReunionCaRoute } from "./pv-reunion-ca";
import { acteCessionPartsRoute } from "./acte-cession-parts";
import { bulletinSouscriptionAugmentationRoute } from "./bulletin-souscription-augmentation";
import { bulletinSouscriptionConstitutionRoute } from "./bulletin-souscription-constitution";
import { feuillePresenceAgSaRoute } from "./feuille-presence-ag-sa";
import { pouvoirAgSaRoute } from "./pouvoir-ag-sa";
import { lettreAppelFondsRoute } from "./lettre-appel-fonds";
import { miseEnDemeureDefaillantRoute } from "./mise-en-demeure-defaillant";
import { pvCarenceAgoRoute } from "./pv-carence-ago";
import { pvCarenceAgeRoute } from "./pv-carence-age";
import { renonciationDroitsSouscriptionRoute } from "./renonciation-droits-souscription";
import { requeteDesignationCacRoute } from "./requete-designation-cac";
import { pacteActionnairesRoute } from "./pacte-actionnaires";
import { decActionnaireUniqueAgRoute } from "./dec-actionnaire-unique-ag";
import { decActionnaireUniqueNonAgRoute } from "./dec-actionnaire-unique-non-ag";
import { pvAgoSaRoute } from "./pv-ago-sa";
import { pvAgeSaRoute } from "./pv-age-sa";
import { pvDissolutionLiquidationRoute } from "./pv-dissolution-liquidation";
import { projetFusionRoute } from "./projet-fusion";
import { rapportCaDissolutionRoute } from "./rapport-ca-dissolution";
import { pvCaDissolutionRoute } from "./pv-ca-dissolution";
import { projetResolutionsDissolutionRoute } from "./projet-resolutions-dissolution";
import { pvAgeDissolutionRoute } from "./pv-age-dissolution";
import { publicationNominationLiquidateurRoute } from "./publication-nomination-liquidateur";
import { lettreNotificationRepresentantRoute } from "./lettre-notification-representant";
import { projetFusionParticipationRoute } from "./projet-fusion-participation";
import { projetFusionSocieteNouvelleRoute } from "./projet-fusion-societe-nouvelle";
import { sncRoute } from "./snc";
import { scsRoute } from "./scs";

export const generateRoutes = Router();

generateRoutes.use(sarlRoute);
generateRoutes.use(sarluRoute);
generateRoutes.use(saAgRoute);
generateRoutes.use(saUniRoute);
generateRoutes.use(saCaRoute);
generateRoutes.use(sasuRoute);
generateRoutes.use(sasRoute);
generateRoutes.use(gieRoute);
generateRoutes.use(stePartRoute);
generateRoutes.use(drcRoute);
generateRoutes.use(pvAgoRoute);
generateRoutes.use(pvAgeRoute);
generateRoutes.use(convAgoRoute);
generateRoutes.use(convAgeRoute);
generateRoutes.use(pouvoirAgRoute);
generateRoutes.use(feuillePresenceRoute);
generateRoutes.use(rapportGestionRoute);
generateRoutes.use(pouvoirCaRoute);
generateRoutes.use(avisConvocationAgSaRoute);
generateRoutes.use(convocationActionnairesSaRoute);
generateRoutes.use(lettreInfoCaConventionsRoute);
generateRoutes.use(avisCacConventionsSaRoute);
generateRoutes.use(avisCacConventionsSarlRoute);
generateRoutes.use(feuillePresenceCaRoute);
generateRoutes.use(lettreConsultationGeranceRoute);
generateRoutes.use(pvConsultationEcriteRoute);
generateRoutes.use(decAssocieUniqueGerantRoute);
generateRoutes.use(decAssocieUniqueNonGerantRoute);
generateRoutes.use(pvReunionCaRoute);
generateRoutes.use(acteCessionPartsRoute);
generateRoutes.use(bulletinSouscriptionAugmentationRoute);
generateRoutes.use(bulletinSouscriptionConstitutionRoute);
generateRoutes.use(feuillePresenceAgSaRoute);
generateRoutes.use(pouvoirAgSaRoute);
generateRoutes.use(lettreAppelFondsRoute);
generateRoutes.use(miseEnDemeureDefaillantRoute);
generateRoutes.use(pvCarenceAgoRoute);
generateRoutes.use(pvCarenceAgeRoute);
generateRoutes.use(renonciationDroitsSouscriptionRoute);
generateRoutes.use(requeteDesignationCacRoute);
generateRoutes.use(pacteActionnairesRoute);
generateRoutes.use(decActionnaireUniqueAgRoute);
generateRoutes.use(decActionnaireUniqueNonAgRoute);
generateRoutes.use(pvAgoSaRoute);
generateRoutes.use(pvAgeSaRoute);
generateRoutes.use(pvDissolutionLiquidationRoute);
generateRoutes.use(projetFusionRoute);
generateRoutes.use(rapportCaDissolutionRoute);
generateRoutes.use(pvCaDissolutionRoute);
generateRoutes.use(projetResolutionsDissolutionRoute);
generateRoutes.use(pvAgeDissolutionRoute);
generateRoutes.use(publicationNominationLiquidateurRoute);
generateRoutes.use(lettreNotificationRepresentantRoute);
generateRoutes.use(projetFusionParticipationRoute);
generateRoutes.use(projetFusionSocieteNouvelleRoute);
generateRoutes.use(sncRoute);
generateRoutes.use(scsRoute);
