import { Router } from "express";
import { sarlRoute } from "./sarl";
import { sarluRoute } from "./sarlu";
import { saAgRoute } from "./sa-ag";
import { saUniRoute } from "./sa-uni";
import { saCaRoute } from "./sa-ca";
import { sasuRoute } from "./sasu";
import { sasRoute } from "./sas";
import { gieRoute } from "./gie";
import { stePartRoute } from "./ste-part";
import { drcRoute } from "./drc";
import { pvAgoRoute } from "./pv-ago";
import { pvAgeRoute } from "./pv-age";
import { convAgoRoute } from "./conv-ago";
import { convAgeRoute } from "./conv-age";
import { pouvoirAgRoute } from "./pouvoir-ag";
import { feuillePresenceRoute } from "./feuille-presence";
import { rapportGestionRoute } from "./rapport-gestion";
import { pouvoirCaRoute } from "./pouvoir-ca";
import { avisConvocationAgSaRoute } from "./avis-convocation-ag-sa";
import { convocationActionnairesSaRoute } from "./convocation-actionnaires-sa";
import { lettreInfoCaConventionsRoute } from "./lettre-info-ca-conventions";
import { avisCacConventionsSaRoute } from "./avis-cac-conventions-sa";
import { avisCacConventionsSarlRoute } from "./avis-cac-conventions-sarl";
import { feuillePresenceCaRoute } from "./feuille-presence-ca";
import { lettreConsultationGeranceRoute } from "./lettre-consultation-gerance";
import { pvConsultationEcriteRoute } from "./pv-consultation-ecrite";
import { decAssocieUniqueGerantRoute } from "./dec-associe-unique-gerant";
import { decAssocieUniqueNonGerantRoute } from "./dec-associe-unique-non-gerant";
import { pvReunionCaRoute } from "./pv-reunion-ca";

export const generateRoutes = Router();

generateRoutes.use(sarlRoute);
generateRoutes.use(sarluRoute);
generateRoutes.use(saAgRoute);
generateRoutes.use(saUniRoute);
generateRoutes.use(saCaRoute);
generateRoutes.use(sasuRoute);
generateRoutes.use(sasRoute);
generateRoutes.use(gieRoute);
generateRoutes.use(stePartRoute);
generateRoutes.use(drcRoute);
generateRoutes.use(pvAgoRoute);
generateRoutes.use(pvAgeRoute);
generateRoutes.use(convAgoRoute);
generateRoutes.use(convAgeRoute);
generateRoutes.use(pouvoirAgRoute);
generateRoutes.use(feuillePresenceRoute);
generateRoutes.use(rapportGestionRoute);
generateRoutes.use(pouvoirCaRoute);
generateRoutes.use(avisConvocationAgSaRoute);
generateRoutes.use(convocationActionnairesSaRoute);
generateRoutes.use(lettreInfoCaConventionsRoute);
generateRoutes.use(avisCacConventionsSaRoute);
generateRoutes.use(avisCacConventionsSarlRoute);
generateRoutes.use(feuillePresenceCaRoute);
generateRoutes.use(lettreConsultationGeranceRoute);
generateRoutes.use(pvConsultationEcriteRoute);
generateRoutes.use(decAssocieUniqueGerantRoute);
generateRoutes.use(decAssocieUniqueNonGerantRoute);
generateRoutes.use(pvReunionCaRoute);
